### ISSUE TITLE
Does not work with e10s

### ISSUE THREAD

**Issue by streetwolf** [nkestrel/dragselectlinktext#1]
Does not work with e10s.

**Comment by nazar-pc** [comment]
+1 Here, any news?

**Comment by nkestrel** [comment]
Was waiting on [Bug 1075670](https://bugzilla.mozilla.org/show_bug.cgi?id=1075670) which has just recently been fixed. 

Drag & drop still depends on [Bug 936092](https://bugzilla.mozilla.org/show_bug.cgi?id=936092).

**Comment by nkestrel** [comment]
The drag & drop bug has been fixed and all seems to be working.
