### ISSUE TITLE
Doesn't work well with CSS transforms

### ISSUE THREAD

**Issue by DerpMcDerp** [nkestrel/dragselectlinktext#11]
e.g. trying to select:

```html
<div style="transform:translate(4ex, 4ex)">
  Some random text.
  <a href="https://www.github.com">Insert some random text here<br>
  blah blah blah blah</a>
  More random text.
</div>
```

acts wonky.

The normal alt+left click text selection in firefox works fine.

**Comment by nkestrel** [comment]
Thanks for reporting this, seems to be a bug with Firefox.

[Bug 1025815 - Incorrect result of document.caretPositionFromPoint after CSS transform](https://bugzilla.mozilla.org/show_bug.cgi?id=1025815)

**Comment by nkestrel** [comment]
Fixed in Nightly 62.
