### ISSUE TITLE
Does not work at addons.mozilla.org

### ISSUE THREAD

**Issue by TestUser013** [nkestrel/dragselectlinktext#13]
Hi,
Thank you for the add-on. It's very useful. But I can't select text at addons.mozilla.org site.

Just try to select "Kestrel" login on the main page of add-on.
https://addons.mozilla.org/uk/firefox/addon/drag-select-link-text

Could you please fix it?

**Comment by nkestrel** [comment]
Firefox blocks extensions from `addons.mozilla.org` for security reasons.

If you are aware of the risks and still want extensions to work there, go to `about:config` and remove `addons.mozilla.org` from `extensions.webextensions.restrictedDomains`  and set `privacy.resistFingerprinting.block_mozAddonManager = true`.

**Comment by TestUser013** [comment]
Thanks! I didn't know about such config properties and was confused when try your plugin. 
You did a great job. Dragselectlinktext is very useful.
