### ISSUE TITLE
The selected text does not fall into the primary buffer in Linux

### ISSUE THREAD

**Issue by KOT040188** [nkestrel/dragselectlinktext#17]
I have linux. When I select the text, it will go to the primary buffer. But when I select the text in the link it doesn't happen.
Firefox 95.0.2, openSUSE Tumbleweed.

**Comment by nkestrel** [comment]
This is a limitation of programmatic selection in Firefox ([Bug 1015877](https://bugzilla.mozilla.org/show_bug.cgi?id=1015877)). Closing as duplicate of #6.
