### ISSUE TITLE
Not working on SeaMonkey 2.39a1

### ISSUE THREAD

**Issue by Exalm** [nkestrel/dragselectlinktext#2]
The extension doesn't work with the latest SeaMonkey 2.39a1 (nightly) on Linux x86_64.
There aren't any errors in error console, and it doesn't seem to do anything at all in neither mode.

**Comment by nkestrel** [comment]
The script isn't being loaded into the page, looks like a bug with the addon SDK.

Affects SeaMonkey 2.36a1-2.39a1

[Bug 1193238](https://bugzilla.mozilla.org/show_bug.cgi?id=1193238)

**Comment by nkestrel** [comment]
Fixed in SeaMonkey 2.40+.
