### ISSUE TITLE
Fails on udemy

### ISSUE THREAD

**Issue by mrx23dot** [nkestrel/dragselectlinktext#20]
Doesn't allow me selecting XZ from "Created by XZ"
on
https://www.udemy.com/course/build-a-passive-income-dividend-portfolio-in-12-easy-steps/

**Comment by nkestrel** [comment]
Enable the "Override unselectable text" setting.
![drag-select-link-text-override](https://github.com/nkestrel/dragselectlinktext/assets/9861435/bee93adb-8327-431d-8f98-f0176ef22e0e)

**Comment by mrx23dot** [comment]
Thank you that works, what's point of that being off by default?
The reason for someone to install the addon is to select anything.

**Comment by arch88** [comment]
> Thank you that works, what's point of that being off by default? The reason for someone to install the addon is to select anything.

I was just having issues with online image editors like Photopea; when clicking and dragging to draw, it selects and drags the canvas. The solution was to disable that option. Something to keep in mind when enabling it. Although it would be interesting to be able to define an exclusion list where the addon is deactivated by default.
