### ISSUE TITLE
[enhancement ideas] drag/hold separation & cancel dragging

### ISSUE THREAD

**Issue by harl** [nkestrel/dragselectlinktext#3]
Hey.
Here are two feature ideas:

1) an option(!) to separate the (horizontal) drag mechanism from the "select all" hold mechanism, so that (accidentally or deliberately) keeping the button pressed doesn't select the whole link if the drag gesture is set to "horizontal". (This could be an option to enable/disable the "select all" procedure in general, or just in conjunction with the horizontal drag gesture.)

2) some way to cancel dragging text/links/images, possibly even when the dragged element had not been highlighted/handled with the help of Drag-Select Link Text before, so that it's easier than pressing Esc. (This could be just right-clicking while dragging, which doesn't open the context menu anyway, and shouldn't do so after cancelling the dragging, at least on standard html/xml web pages). - (This would be especially helpful to anyone using an add-on like DragToGo that doesn't need elements to be dragged to the tabs bar to open them in a new tab.)

--
(Drag-Select Link Text works very well with Firefox Nightly 54.0a1 (2017-02-20) (32-bit), e10s enabled, on Windows 10 Pro (64-bit). - I wasn't able to reproduce the supposed bug/glitch (with the "select all" feature) mentioned by the user "ale" on AMO, either.)

**Comment by nkestrel** [comment]
Thanks for the feedback.

1. This shouldn't need an extra option as it can be effectively disabled by specifying a large hold time.

2. This falls outside the scope of this extension and would be more appropriate for extensions that provide drag actions like the one you mentioned.
