### ISSUE TITLE
Crashing FF 55 and 56 when clicking hamburger menu

### ISSUE THREAD

**Issue by piejanssens** [nkestrel/dragselectlinktext#4]
This addon is making my FF crash on version 55 and now 56.
When disabled and trying to enable it it also crashes FF.

**Comment by nkestrel** [comment]
Thanks for the report.

I can't reproduce a crash when opening the hamburger menu.

I do sometimes get a crash when enabling the extension ([Bug 1363301](https://bugzilla.mozilla.org/show_bug.cgi?id=1363301)).

Can you provide a link to a crash report from `about:crashes` for each case?

**Comment by piejanssens** [comment]
The crash only happens on MacOS. Let me know how I can assist you with more info.

**Comment by nkestrel** [comment]
[Bug 1363301](https://bugzilla.mozilla.org/show_bug.cgi?id=1363301) has been fixed on Beta 55.0b3 and Nightly 56. The 1.5.1 update has been released making it a full WebExtension. Are you still getting crashes now?

**Comment by piejanssens** [comment]
No more crashes.
