### ISSUE TITLE
Dropdown list auto-closing

### ISSUE THREAD

**Issue by nkestrel** [nkestrel/dragselectlinktext#8]
[User report](https://addons.mozilla.org/en-US/firefox/addon/drag-select-link-text/reviews/1014532/) of dropdown list closing by itself [on Discord](https://discordapp.com/oauth2/authorize?client_id=263621237127905280&scope=bot&permissions=0). 

I couldn't reproduce this exact issue on Windows 10 or Ubuntu 17.10 however with `Override unselectable text` enabled the dropdown list sometimes flickers slightly on mouseup which might be related. Discord is preventing selection and when the override class is removed on mouseup it coincides with the list flashing. 

Exclude `<select>` elements since they contain nothing selectable anyway.

**Comment by Evengard** [comment]
I was the mentioned user who reported the problem.

Anyway, seems like the problem went away with 1.5.4beta1. Seems like that flicker you mentioned actually completely hid the select menu for me.

As a side note, I enabled the webrender (Quantum Renderer) about:config switches (gfx.webrender.enabled and others), that may be related to the bug.

**Comment by nkestrel** [comment]
Thanks for testing and confirming it is fixed. These kinds of bugs are expected with WebRender given its current unstable state.

FWIW I was unable to reproduce your exact issue with `gfx.webrender.all = true` on Nightly with Windows or Linux so it is most likely hardware dependent.
