### ISSUE TITLE
XML files are rendered as plain text after selecting

### ISSUE THREAD

**Issue by jonlt** [nkestrel/dragselectlinktext#9]
Hi, thanks for a great add-on! 

There seems to be an issue with XML files, they are being displayed as plain text when the add-on is active.
Reproduce:

1) Activate/install the add-on
2) open an xml file (e.g. https://www.w3schools.com/xml/note.xml) 
3) select some text in the file

**What happens**
The XML file is displayed as plain text:
> ![bug](https://user-images.githubusercontent.com/292698/35030862-eac945d4-fb60-11e7-9958-bd93f0d7320f.gif)

**What I expected would happen**
The text would be selected in the XML structure (as in this screenshot where the add-on is disabled):
> ![no-bug](https://user-images.githubusercontent.com/292698/35030871-f01da12e-fb60-11e7-9abf-3cdf5ba591c5.gif)

**Comment by Evengard** [comment]
Can confirm. Never thought it was because of the addon though.

**Comment by jonlt** [comment]
Looks like it is caused by manipulating the classList of the elements in the document. This code (copied into the console), reproduces the issue:

    document.onclick = function(e){e.target.classList.add("test");}

**Comment by Evengard** [comment]
I've added a tentative fix for the issue. Basically I'm just filtering out all non-HTMLDocument documents with it.

**Comment by jonlt** [comment]
That would fix it. A less intrusive solution would be fixing it at the manifest-level - if that is possible?

**Comment by nkestrel** [comment]
Thanks for reporting this issue, Firefox's XML viewer is quite sensitive it seems ([Bug 1401793](https://bugzilla.mozilla.org/show_bug.cgi?id=1401793)).

**Comment by nkestrel** [comment]
Fixed in [1.5.4beta2](https://addons.mozilla.org/en-US/firefox/addon/drag-select-link-text/versions/1.5.4beta2).

**Comment by Evengard** [comment]
Do you plan to publish this beta version as a non-beta?

**Comment by nkestrel** [comment]
[1.5.4 release version is available on AMO](https://addons.mozilla.org/en-US/firefox/addon/drag-select-link-text/versions/1.5.4).
